### ISSUE TITLE
Filemanager not making screenshots & not showing images or videos

### ISSUE THREAD

**Issue by MReda909** [nelu/rutorrent-filemanager-media#3]
As the title says, filemanager-media isn't showing images or videos, it reads text and nfo files perfectly but images show the broken image thumbnails and videos just black screen... it can detect file size and dimensions in mediainfo and files are not broken.. i think i might have missed something while installing but i changed the domain in conf.php file to my domain but still nothing works..

**Comment by nelu** [comment]
Try the latest release, that should fix some of the issues
